version: '3.8'

services:
  php-apache:
    build: .
    container_name: simple_php_website
    ports:
      - "8080:80" # Map port 8080 on your host to port 80 in the container
    volumes:
      - ./src:/var/www/html # Mount the project files for live updates
    restart: always
