name: Deploy PHP Application to AWS EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: SSH into EC2 and Deploy
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Update package list and install necessary packages
          sudo apt update
          sudo apt install -y apache2 php libapache2-mod-php git unzip

          # Navigate to the web root directory
          DEPLOY_DIR=/sample_php_app
          sudo rm -rf $DEPLOY_DIR/*
          sudo chown -R ubuntu:ubuntu $DEPLOY_DIR
          cd $DEPLOY_DIR

          # Clone the latest code from the GitHub repository
          if [ ! -d ".git" ]; then
            git https://github.com/code-wizard-18/sample_php_app.git .
          else
            git reset --hard
            git pull origin dev
          fi

          # Ensure proper file permissions
          sudo chown -R www-data:www-data $DEPLOY_DIR
          sudo chmod -R 755 $DEPLOY_DIR

          # Restart Apache to apply changes
          sudo systemctl restart apache2
